version: "3.8"

services:
  hub:
    build: ./hub-app
    image: ghcr.io/kaamichaud02/hub:dev
    container_name: hub-kaa-zone
    restart: unless-stopped
    environment:
      - HUB_DB_HOST=${HUB_DB_HOST}
      - HUB_DB_PORT=${HUB_DB_PORT:-5432}
      - HUB_DB_NAME=${HUB_DB_NAME:-hub_kaa_zone}
      - HUB_DB_USER=${HUB_DB_USER}
      - HUB_DB_PASSWORD=${HUB_DB_PASSWORD}
    ports:
      - "8420:8000"
